"""
Mizan GRC - Export Utilities
Functions for generating downloadable documents (DOCX, Excel, PDF).
"""

import io
from datetime import datetime
from typing import Dict, Any, List
import pandas as pd

# Try to import document generation libraries
try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    HAS_PDF = True
except ImportError:
    HAS_PDF = False


def generate_strategy_docx(
    org_name: str,
    domain: str,
    sections: Dict[str, str],
    roadmap_df: pd.DataFrame,
    language: str = "English"
) -> bytes:
    """Generate a Word document for the strategy."""
    if not HAS_DOCX:
        return None
    
    doc = Document()
    
    # Title
    title = doc.add_heading(f"Strategic Roadmap: {org_name}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    doc.add_paragraph(f"Domain: {domain}")
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph(f"Language: {language}")
    doc.add_paragraph("─" * 50)
    
    # Section titles based on language
    if language == "Arabic":
        section_names = {
            "vision": "الرؤية التنفيذية والأهداف الاستراتيجية",
            "gaps": "تقييم الوضع الراهن (تحليل الفجوات)",
            "pillars": "الركائز الاستراتيجية والمبادرات",
            "roadmap": "خارطة طريق التنفيذ",
            "kpis": "قياس النجاح (مؤشرات الأداء والمخاطر)",
            "confidence": "درجة الثقة والتحقق"
        }
    else:
        section_names = {
            "vision": "Executive Vision & Strategic Objectives",
            "gaps": "Current State Assessment (Gap Analysis)",
            "pillars": "Strategic Pillars & Initiatives",
            "roadmap": "Implementation Roadmap",
            "kpis": "Measuring Success (KPIs & KRIs)",
            "confidence": "Confidence Score & Validation"
        }
    
    # Add sections
    for key in ["vision", "gaps", "pillars", "roadmap", "kpis", "confidence"]:
        doc.add_heading(section_names.get(key, key), level=1)
        content = sections.get(key, "N/A")
        # Handle RTL for Arabic
        para = doc.add_paragraph(content)
        if language == "Arabic":
            para.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        doc.add_paragraph()
    
    # Add roadmap table if available
    if not roadmap_df.empty:
        doc.add_heading("Implementation Timeline", level=1)
        
        # Create table
        table = doc.add_table(rows=1, cols=6)
        table.style = 'Table Grid'
        
        # Header row
        headers = ["Phase", "Initiative", "Duration", "Cost (SAR)", "Owner", "KPI"]
        header_cells = table.rows[0].cells
        for i, header in enumerate(headers):
            header_cells[i].text = header
        
        # Data rows
        for _, row in roadmap_df.iterrows():
            row_cells = table.add_row().cells
            row_cells[0].text = str(row.get("Phase", ""))
            row_cells[1].text = str(row.get("Initiative", ""))
            row_cells[2].text = str(row.get("Duration", ""))
            row_cells[3].text = f"{row.get('Cost', 0):,.0f}"
            row_cells[4].text = str(row.get("Role", ""))
            row_cells[5].text = str(row.get("KPI", ""))
    
    # Save to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def generate_policy_docx(
    policy_name: str,
    domain: str,
    framework: str,
    content: str,
    language: str = "English"
) -> bytes:
    """Generate a Word document for a policy."""
    if not HAS_DOCX:
        return None
    
    doc = Document()
    
    # Title
    title = doc.add_heading(policy_name, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    doc.add_paragraph(f"Domain: {domain}")
    doc.add_paragraph(f"Reference Framework: {framework}")
    doc.add_paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph(f"Document Status: DRAFT - Requires Review")
    doc.add_paragraph("─" * 50)
    
    # Content
    para = doc.add_paragraph(content)
    if language == "Arabic":
        para.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    
    # Footer
    doc.add_paragraph()
    doc.add_paragraph("─" * 50)
    doc.add_paragraph("This document was generated by Mizan GRC and requires review before implementation.")
    
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def generate_risk_register_excel(
    risks_df: pd.DataFrame,
    domain: str = "All"
) -> bytes:
    """Generate an Excel file for the risk register."""
    buffer = io.BytesIO()
    
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        # Main risk register sheet
        if not risks_df.empty:
            risks_df.to_excel(writer, sheet_name='Risk Register', index=False)
            
            # Get workbook and worksheet
            workbook = writer.book
            worksheet = writer.sheets['Risk Register']
            
            # Add formatting
            header_format = workbook.add_format({
                'bold': True,
                'bg_color': '#2563EB',
                'font_color': 'white',
                'border': 1
            })
            
            # Apply header format
            for col_num, value in enumerate(risks_df.columns.values):
                worksheet.write(0, col_num, value, header_format)
            
            # Auto-fit columns
            for i, col in enumerate(risks_df.columns):
                max_len = max(risks_df[col].astype(str).map(len).max(), len(col)) + 2
                worksheet.set_column(i, i, min(max_len, 50))
        else:
            # Empty template
            template_df = pd.DataFrame(columns=[
                'Risk ID', 'Domain', 'Asset', 'Category', 'Threat/Risk',
                'Probability', 'Impact', 'Risk Score', 'Risk Level',
                'Mitigation', 'Owner', 'Status', 'Due Date'
            ])
            template_df.to_excel(writer, sheet_name='Risk Register', index=False)
        
        # Summary sheet
        summary_data = {
            'Metric': ['Total Risks', 'Critical', 'High', 'Medium', 'Low', 'Domain'],
            'Value': [
                len(risks_df) if not risks_df.empty else 0,
                len(risks_df[risks_df['risk_level'] == 'CRITICAL']) if not risks_df.empty and 'risk_level' in risks_df.columns else 0,
                len(risks_df[risks_df['risk_level'] == 'HIGH']) if not risks_df.empty and 'risk_level' in risks_df.columns else 0,
                len(risks_df[risks_df['risk_level'] == 'MEDIUM']) if not risks_df.empty and 'risk_level' in risks_df.columns else 0,
                len(risks_df[risks_df['risk_level'] == 'LOW']) if not risks_df.empty and 'risk_level' in risks_df.columns else 0,
                domain
            ]
        }
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_excel(writer, sheet_name='Summary', index=False)
    
    buffer.seek(0)
    return buffer.getvalue()


def generate_roadmap_excel(
    roadmap_df: pd.DataFrame,
    org_name: str = "Organization",
    domain: str = "All"
) -> bytes:
    """Generate an Excel file for the roadmap."""
    buffer = io.BytesIO()
    
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        workbook = writer.book
        
        # Roadmap sheet
        if not roadmap_df.empty:
            # Select and rename columns for export
            export_cols = ['Phase', 'Initiative', 'Duration', 'Cost', 'Role', 'KPI']
            available_cols = [c for c in export_cols if c in roadmap_df.columns]
            export_df = roadmap_df[available_cols].copy()
            
            export_df.to_excel(writer, sheet_name='Roadmap', index=False)
            
            worksheet = writer.sheets['Roadmap']
            
            # Header format
            header_format = workbook.add_format({
                'bold': True,
                'bg_color': '#10B981',
                'font_color': 'white',
                'border': 1
            })
            
            # Currency format
            currency_format = workbook.add_format({'num_format': '#,##0'})
            
            # Apply header format
            for col_num, value in enumerate(export_df.columns.values):
                worksheet.write(0, col_num, value, header_format)
            
            # Apply currency format to Cost column
            if 'Cost' in export_df.columns:
                cost_col = export_df.columns.get_loc('Cost')
                worksheet.set_column(cost_col, cost_col, 15, currency_format)
            
            # Auto-fit columns
            for i, col in enumerate(export_df.columns):
                max_len = max(export_df[col].astype(str).map(len).max(), len(col)) + 2
                worksheet.set_column(i, i, min(max_len, 40))
        
        # Summary sheet
        total_cost = roadmap_df['Cost'].sum() if not roadmap_df.empty and 'Cost' in roadmap_df.columns else 0
        total_duration = roadmap_df['Duration'].sum() if not roadmap_df.empty and 'Duration' in roadmap_df.columns else 0
        
        summary_data = {
            'Metric': ['Organization', 'Domain', 'Total Initiatives', 'Total Investment (SAR)', 'Total Duration (Months)', 'Generated'],
            'Value': [org_name, domain, len(roadmap_df), f"{total_cost:,.0f}", f"{total_duration:.1f}", datetime.now().strftime('%Y-%m-%d')]
        }
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_excel(writer, sheet_name='Summary', index=False)
    
    buffer.seek(0)
    return buffer.getvalue()


def generate_audit_docx(
    standard: str,
    content: str,
    language: str = "English"
) -> bytes:
    """Generate a Word document for audit report."""
    if not HAS_DOCX:
        return None
    
    doc = Document()
    
    # Title
    title = doc.add_heading(f"Audit Report: {standard}", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Metadata
    doc.add_paragraph(f"Audit Standard: {standard}")
    doc.add_paragraph(f"Report Date: {datetime.now().strftime('%Y-%m-%d')}")
    doc.add_paragraph(f"Status: DRAFT - Requires Review")
    doc.add_paragraph("─" * 50)
    
    # Content
    para = doc.add_paragraph(content)
    if language == "Arabic":
        para.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
